### ISSUE TITLE
example can not be built by default now

### ISSUE THREAD

**Issue by QuinnWang** [xmos/lib_xcore_math#104]
This command doesn't work as there is no xmos_toolchain.cmake in the etc directory
_mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../etc/xmos_toolchain.cmake -G"Unix Makefiles" .._

**Comment by astewart-xmos** [comment]
Thanks, the documentation will need to be updated.

To build examples currently CMake should be configured with:

    mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../etc/xmos_cmake_toolchain/xs3a.cmake -DDEV_LIB_XCORE_MATH=1 -G"Unix Makefiles" ..
    
 Note that `/etc/xmos_cmake_toolchain/` is a submodule, so when `lib_xcore_math` is cloned, submodules will also need to be updated.

The `-DDEV_LIB_XCORE_MATH=1` should ensure the examples are added as targets.
