### ISSUE TITLE
Bug in vect_packed_complex_f32_macc() 

### ISSUE THREAD

**Issue by lucianomartin** [xmos/lib_xcore_math#116]
The Input/Output accumulator vector must be incremented before it is assigned in [vect_packed_complex_f32_macc()](https://github.com/xmos/lib_xcore_math/blob/develop/lib_xcore_math/src/vect/vect_f32.c#L46):

```
  a[0].re = b[0].re * c[0].re;
  a[0].im = b[0].im * c[0].im;
```

must be

```
  a[0].re += b[0].re * c[0].re;
  a[0].im += b[0].im * c[0].im;
```

The same as in [vect_packed_complex_f32_conj_macc()](https://github.com/xmos/lib_xcore_math/blob/develop/lib_xcore_math/src/vect/vect_f32.c#L58).

**Comment by astewart-xmos** [comment]
This issue has been addressed in PR https://github.com/xmos/lib_xcore_math/pull/120 and a fix will be available in `v2.1.1`
