### ISSUE TITLE
scalar float conversion functions -- duplicates and missing from API

### ISSUE THREAD

**Issue by astewart-xmos** [xmos/lib_xcore_math#124]
I must have messed up during previous updates, because there are some issues with the functions for converting to/from `float` values.

* `util.S` defines functions that are no longer in the API.
  * Did I forget to add them to the API, or did I forget to delete `util.S`?
* Some of the C implementations of the scalar functions use the `double` versions of standard library math functions
  * e.g. `frexp()` instead of `frexpf()` and `ldexp()` instead of `ldexpf()`
* Why do both `float_s32_to_f32()`  and `float_s32_to_float()` exist?
* Why do both `unpack_float()` and `f32_unpack()` exist?

As far as I can tell, all four implementations are functionally correct.

(Thanks to @shuchitak for bringing this to my attention)

**Comment by mbanth** [comment]
This issue is now tracked in Jira [AP-156](https://xmosjira.atlassian.net/browse/AP-156).
