### ISSUE TITLE
Windows build issues

### ISSUE THREAD

**Issue by jcarrier-xmos** [xmos/lib_xcore_math#135]
When building on native-Windows (via either MSVC/MSBuild, NMake, or Ninja) the underlying compiler `cl.exe` reports invalid arguments related to the target_compile_options in `CMakeLists.txt`.

For example:
`cl : Command line error D8021 : invalid numeric argument '/Wno-format'`

This applies to:
```
-Wno-format 
-Wno-unused-variable 
-Wno-missing-braces
```

Additionally, it reports:

`cl : Command line warning D9002 : ignoring unknown option '-g'`

After resolving these issues, `M_PI` is reported as not being defined:

`src\scalar\scalar_f32.c(53): error C2065: 'M_PI': undeclared identifier`

According to this:
https://learn.microsoft.com/en-us/cpp/c-runtime-library/math-constants?view=msvc-170

A preprocessor define `_USE_MATH_DEFINES` should be set to activate this constant.

**Comment by keithm-xmos** [comment]
@jcarrier-xmos Are you able to fix this and submit a PR?

**Comment by mbanth** [comment]
This issue is now tracked in Jira [AP-124](https://xmosjira.atlassian.net/browse/AP-124).
