### ISSUE TITLE
XS3_BFP_DEBUG_CHECK_LENGTHS: bug in assert

### ISSUE THREAD

**Issue by rhd-idmt** [xmos/lib_xcore_math#146]
In file bfp_s32.c, there are two wrong asserts:
In functions
void bfp_s32_macc(...)
void bfp_s32_nmacc(...)
it should say

assert(b->length == acc->length);

instead of

assert(b->length == a->length);

Kind regards
Marco

**Comment by mbanth** [comment]
This issue is now tracked in Jira [AP-122](https://xmosjira.atlassian.net/browse/AP-122).

**Comment by uvvpavel** [comment]
Hi @rhd-idmt, thank you for reporting this bug. It has been fixed in the recent push to the ``develop`` branch, hope you have a great experience using ``lib_xcore_math`` ✨
