### ISSUE TITLE
Missing function definition for s16_to_s32() in lib_xcore_math/lib_xcore_math/api/xmath/scalar/s16.h

### ISSUE THREAD

**Issue by VergilWang15** [xmos/lib_xcore_math#147]
**Issue:**
The function definition for s16_to_s32() is missing in the file lib_xcore_math/lib_xcore_math/api/xmath/scalar/s16.h.
It seems that the implementation of this function is present in the file lib_xcore_math/lib_xcore_math/src/scalar/scalar_ops.c, but with a different name - scalar_s16_to_s32().

**Expected Behavior:**
The s16_to_s32() function should have a corresponding function definition in the s16.h header file with the correct name.

**Steps to Reproduce:**
Navigate to the file lib_xcore_math/lib_xcore_math/api/xmath/scalar/s16.h.
Search for the function definition of s16_to_s32().

**Actual Results:**
The function definition for s16_to_s32() is not found in the s16.h header file.

**Additional Information:**
It appears there was a naming mismatch between the header file and the source file. The function definition in the source file should be renamed to match the expected name in the header file. This can cause confusion and hinder the usability of the library. It would be helpful to update either the header file or the source file to ensure consistency and maintainability.

**Comment by mbanth** [comment]
This issue is now tracked in Jira [AP-123](https://xmosjira.atlassian.net/browse/AP-123).

**Comment by uvvpavel** [comment]
Hi @VergilWang15, thank you for reporting this bug. It has been fixed in the recent push to the ``develop`` branch, hope you have a great experience using ``lib_xcore_math`` ✨
