### ISSUE TITLE
Alignment Issues with Latex Equations in lib_xcore_math Documentation

### ISSUE THREAD

**Issue by VergilWang15** [xmos/lib_xcore_math#167]
**Introduction:**
This issue report aims to highlight alignment problems with Latex equations in the XCORE Software Development Kit (SDK) documentation. Specifically, we will examine two examples from the XCORE SDK documentation where incorrect alignment symbols (`&`) have been added to the rendered Latex code on the webpage.

**Example 1: vect_s32_rect**
Link: [vect_s32_rect](https://www.xmos.com/documentation/XM-014926-PC-1/html/modules/core/modules/xcore_math/lib_xcore_math/doc/programming_guide/src/reference/vect/vect_s32.html#c.vect_s32_rect)

**Example 2: vect_s32_clip**
Link: [vect_s32_clip](https://www.xmos.com/documentation/XM-014926-PC-1/html/modules/core/modules/xcore_math/lib_xcore_math/doc/programming_guide/src/reference/vect/vect_s32.html#c.vect_s32_clip)

Explanation:
Upon comparing the Latex equations provided on the webpage with the Latex equations present in the API comments, it becomes apparent that some incorrect alignment symbols (`&`) have been added to the rendered Latex code on the webpage.

It seems fine in the comment:
```c
//lib_xcore_math\api\xmath\vect\vect_s32.h#Line359
 * @operation{
 * & b_k' \leftarrow sat_{32}(\lfloor b_k \cdot 2^{-b\_shr} \rfloor) \\
 * & a_k \leftarrow \begin{cases\}
 *           lower\_bound & b_k' \le lower\_bound                        \\
 *           upper\_bound & b_k' \ge upper\_bound                        \\
 *           b_k' & otherwise \end{cases\}                              \\
 * & \qquad\text{ for }k\in 0\ ...\ (length-1)
 * }
```

These lex commands were copied from webpage:
```latex
\begin{split}
\begin{align*} 
& b_k' \leftarrow sat_{32}(\lfloor b_k \cdot 2^{-b\_shr} \rfloor) \\ 
& a_k \leftarrow \begin{cases} 
		lower\_bound & b_k' \le lower\_bound \\ 
		& upper\_bound & b_k' \ge upper\_bound \\ 
		& b_k' & otherwise \end{cases} \\ 
& \qquad\text{ for }k\in 0\ ...\ (length-1) && \end{align*}\end{split}
```
The above code snippet demonstrates how the rendered Latex equation within the `vect_s32_clip` function is affected. Incorrect alignment symbols (`&`) have been introduced, which disrupt the proper formatting and interpretation of the equation.

**Comment by mbanth** [comment]
Thank you, @VergilWang15, for pointing out this problem in our documentation.  I will submit your information to our product management team.  Someone will update this issue as we progress it to a conclusion.

**Comment by mbanth** [comment]
@VergilWang15, the documentation problem you found has been fixed.  This change will appear in the next release of xcore-iot and in the next release of xcore-voice.  Thank you again for alerting us to this issue.
