### ISSUE TITLE
Failure to Render Pages in lib_xcore_math Documentation

### ISSUE THREAD

**Issue by VergilWang15** [xmos/lib_xcore_math#168]
**Description:** 
Some pages in the lib_xcore_math documentation, such as the one for XCORE-SDK, are not being rendered properly. An example of such a page can be found at: [16-Bit Vector Prepare Functions](https://www.xmos.com/documentation/XM-014926-PC-1/html/modules/core/modules/xcore_math/lib_xcore_math/doc/programming_guide/src/reference/vect/vect_s16_prepare.html)

**Issue Details:** 
While inspecting the API source code, I noticed that certain comments are present, but for some reason, they are not being rendered on the documentation web page.

[API link](https://github.com/xmos/lib_xcore_math/blob/develop/lib_xcore_math/api/xmath/vect/vect_s16_prepare.h)
```c
/**
 * @defgroup vect_s16_prepare_api   16-bit Vector Prepare Functions
 */
```

**Comment by mbanth** [comment]
Thank you, VergilWang15, for pointing out this problem with the documentation.  We have investigated and fixed it.  The corrected documentation will be available in the next release of xcore-iot and the next release of xcore-voice.

**Comment by VergilWang15** [comment]
Really glad to see the document getting better :)
