### ISSUE TITLE
More than just adding alpha

### ISSUE THREAD

**Issue by henkmuller** [xmos/lib_xcore_math#169]
https://github.com/xmos/lib_xcore_math/blob/44c3e87a40d4399edfa71eb1e79552930d8faac9/lib_xcore_math/api/xmath/fft.h#L548

It appears that the inverse functions also adjust exp with the gain of a combined FFT/IFFT. If that is the case, this is slightly odd as both the FFT and IFFT have a gain of SQRT(N), and accounting for a gain of N on one of them seems to only be useful if you perform pairs of FFT + IFFT.

**Comment by mbanth** [comment]
For planning purposes, this issue is tracked in Jira [AP-279](https://xmosjira.atlassian.net/browse/AP-279).

**Comment by uvvpavel** [comment]
This issue has been resolved in #176, thanks for raising it ✨
