### ISSUE TITLE
Support building/including from xcommon

### ISSUE THREAD

**Issue by oscarbailey-xmos** [xmos/lib_xcore_math#18]
Currently, this library builds into a static lib archive, but cannot be easily used via the xcommon/xmake build system.

I suggest that this could be achieved by emulating xmake's "library export" feature. See section 12: https://www.xmos.ai/download/xTIMEcomposer-User-Guide-14(14.x).pdf

**UPDATE:** Tested emulating the library export feature and can now successfully compile an "xmake" application + link xs3_math. ~~It doesn't work with waf/xcommon since waf/xcommon doesn't support those features.~~ Linking static libs is supported in waf, see this PR for an extension of that functionality: https://github.com/xmos/tools_waf_xcc/pull/14

The Makefile in this lib could have an extra target e.g. build_xcommon which would create the directory structure that xcommon looks for:
```
export/
└── lib_xs3_math
    ├── include
    │   ├── bfp
    │   │   ├── bfp_ch_pair.h
    │   │   ├── bfp_complex.h
    │   │   ├── bfp_fft.h
    │   │   ├── bfp.h
    │   │   └── bfp_init.h
    │   ├── bfp_math.h
    │   ├── vect
    │   │   ├── xs3_fft.h
    │   │   ├── xs3_filters.h
    │   │   ├── xs3_vect_s16.h
    │   │   └── xs3_vect_s32.h
    │   ├── xs3_math_conf.h
    │   ├── xs3_math.h
    │   ├── xs3_math_types.h
    │   ├── xs3_util.h
    │   ├── xs3_vpu.h
    │   └── xs3_vpu_scalar_ops.h
    ├── lib
    │   ├── xs1b
    │   │   └── libxs3_math.a
    │   └── xs3a
    │       └── libxs3_math.a
    └── module_build_info

7 directories, 19 files
```

In this structure, the `include` directory is a copy of the `api` directory, the `lib/xs1b/libxs3_math.a` file is a copy of the xcore library file i.e. `lib/arch/xcore/lib_xs3_math.a`.

The module build info needs to contain the following:
```
VERSION = 0.0.1

DEPENDENT_MODULES = lib_xassert(>=4.0.0) \
                    lib_logging(>=3.0.0)

OPTIONAL_HEADERS +=

EXPORT_INCLUDE_DIRS = include \
                      include/bfp \
                      include/vect

LIB_DIRS = lib

LIBRARY = xs3_math

EXPORTED = 1
```

For some reason, both `xs1b` folders and `xs3a` folders need to exist for the build to complete successfully. I believe this is because xmake/xcommon has not been updated to support library-linking for xs3: [There are places where it only looks for xs2a or xs1b](https://github0.xmos.com/xmos-int/xcommon/blob/21fe8aaceb04e68ad1ecdc67c7f61ecc29572563/xcommon/module_xcommon/build/Makefile.common1#L700)

The other option is to include and maintain a module_build_info that would allow applications to include and build the library from source. I've tested this module_build_info file and it works with both xmake and waf:
```
VERSION = 0.0.1

DEPENDENT_MODULES = lib_xassert(>=4.0.0) \
                    lib_logging(>=3.0.0)

MODULE_XCC_FLAGS = $(XCC_FLAGS) \
                   -O2

OPTIONAL_HEADERS +=

EXPORT_INCLUDE_DIRS = api \
                      api/bfp \
                      api/vect


INCLUDE_DIRS = $(EXPORT_INCLUDE_DIRS) \
               src \
               src/bfp \
               src/vect


SOURCE_DIRS = src \
              src/arch/xcore \
              src/arch/xcore/complex \
              src/arch/xcore/fft \
              src/arch/xcore/filter \
              src/arch/xcore/stat \
              src/bfp \
              src/vect

```

**Comment by ed-xmos** [comment]
I've just come across this issue and made my own module_build_info which allowed it to build using xcommon (the officially supported build system by the tools group).

`VERSION = 0.1.0

DEPENDENT_MODULES =

MODULE_XCC_FLAGS = $(XCC_FLAGS)

#OPTIONAL_HEADERS += api/xs3_math.h

EXPORT_INCLUDE_DIRS = api api/vect api/bfp

INCLUDE_DIRS = $(EXPORT_INCLUDE_DIRS)

SOURCE_DIRS = src \
              src/arch/xcore \
              src/arch/xcore/complex \
              src/arch/xcore/fft \
              src/arch/xcore/filter \
              src/arch/xcore/stat \
              src/bfp \
              src/vect
`

Let me know if you want me to make a PR. This file will not affect other build systems and so should be harmless to add.
Since we will soon be using xs3_math in the 3610 project (necessary for optimisations to fit in new AEC without winding up the clock speed), this will be needed.
